/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tenpercent_strobe_NativeWrapper */

#ifndef _Included_com_tenpercent_strobe_NativeWrapper
#define _Included_com_tenpercent_strobe_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tenpercent_strobe_NativeWrapper
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_tenpercent_strobe_NativeWrapper_init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_tenpercent_strobe_NativeWrapper
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tenpercent_strobe_NativeWrapper_step
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
